version: '3.9'

networks:
  internal:
    external: false

volumes:
  pgdata:

services:
  app:
    build: ./
    command: ./app
    ports:
      - 8090:8090
    depends_on:
      - postgres
    environment:
      - TZ=Asia/Almaty
      - PORT=${PORT}
      - PgURL=${PgURL}
      - Database=${Database}
      - HMACSecret=${HMACSecret}
    networks:
      - internal

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - /pgdata2:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5436:5432
    networks:
      - internal

  redis:
    image: redis:alpine
    networks:
      - internal
    ports:
      - "6380:6379"

